"""
Statistical Analysis Module — Updated for Master CSV
- Wilcoxon Signed-Rank Test (Pairwise comparison)
- Friedman Rank Test (Global algorithm ranking)
- Mean ± Std tables (LaTeX ready)
- Final Ranking based on Error Value (f(x) - f(x*))
"""
import os
import numpy as np
import pandas as pd
from scipy import stats
from itertools import combinations

# --- VS CODE PATH FIX ---
import sys
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

ALPHA = 0.05   # Significance level for statistical tests

def load_results(csv_path=None) -> pd.DataFrame:
    """Loads the single master CSV generated by run_all.py."""
    if csv_path is None:
        csv_path = os.path.join(project_root, "results", "all_algo_results.csv")
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Master CSV not found at {csv_path}. Run experiments/run_all.py first.")
    
    return pd.read_csv(csv_path)

def summary_table(df: pd.DataFrame, dim: int) -> pd.DataFrame:
    """Generates a Mean ± Std table focused on Error Values."""
    sub = df[df["dim"] == dim]
    
    # Calculate Mean and Std of error_val per Function and Algorithm
    stats_df = sub.groupby(["func_id", "algorithm"])["error_val"].agg(["mean", "std"]).reset_index()
    
    # Format string for paper reporting (Scientific notation)
    stats_df["formatted"] = stats_df.apply(
        lambda x: f"{x['mean']:.2e} ± {x['std']:.1e}", axis=1
    )
    
    # Pivot to make Algorithms the columns
    pivot = stats_df.pivot(index="func_id", columns="algorithm", values="formatted")
    return pivot

def friedman_ranking(df: pd.DataFrame, dim: int) -> pd.DataFrame:
    """
    Computes global ranking using the Friedman test across all functions.
    Lower Average Rank = Better Algorithm.
    """
    sub = df[df["dim"] == dim]
    algos = sorted(sub["algorithm"].unique())
    func_ids = sorted(sub["func_id"].unique())

    # Create matrix: Rows = Functions, Cols = Algorithms (using mean error_val)
    perf_matrix = np.zeros((len(func_ids), len(algos)))
    for i, fid in enumerate(func_ids):
        for j, algo in enumerate(algos):
            mean_err = sub[(sub["func_id"] == fid) & (sub["algorithm"] == algo)]["error_val"].mean()
            perf_matrix[i, j] = mean_err if not np.isnan(mean_err) else 1e10

    # 1. Perform Friedman Test
    # Each column of perf_matrix represents an algorithm's performance across functions
    stat, p_val = stats.friedmanchisquare(*[perf_matrix[:, j] for j in range(len(algos))])
    
    # 2. Calculate Average Ranks
    from scipy.stats import rankdata
    # Rank each row (function) individually
    ranks = np.array([rankdata(row) for row in perf_matrix])
    avg_ranks = ranks.mean(axis=0)

    result = pd.DataFrame({
        "Algorithm": algos,
        "Average_Rank": avg_ranks,
        "Final_Rank": rankdata(avg_ranks).astype(int)
    }).sort_values("Average_Rank")

    print(f"\n--- Friedman Test (D={dim}) ---")
    print(f"Statistic (Chi-square): {stat:.4f}")
    print(f"P-value: {p_val:.4e}")
    if p_val < ALPHA:
        print("Result: Significant difference detected between algorithms.")
    
    return result

def wilcoxon_wtl(df: pd.DataFrame, dim: int) -> pd.DataFrame:
    """
    Pairwise Wilcoxon Signed-Rank Test.
    Calculates Wins/Ties/Losses (W/T/L) for every pair.
    """
    sub = df[df["dim"] == dim]
    algos = sorted(sub["algorithm"].unique())
    fids = sorted(sub["func_id"].unique())
    
    results = []

    for a1, a2 in combinations(algos, 2):
        wins, ties, losses = 0, 0, 0
        
        for fid in fids:
            d1 = sub[(sub["algorithm"] == a1) & (sub["func_id"] == fid)]["error_val"].values
            d2 = sub[(sub["algorithm"] == a2) & (sub["func_id"] == fid)]["error_val"].values
            
            if len(d1) < 2 or len(d2) < 2: continue
            
            try:
                # Two-sided test
                _, p = stats.wilcoxon(d1, d2)
                
                if p < ALPHA:
                    if np.mean(d1) < np.mean(d2): # Lower error is a win
                        wins += 1
                    else:
                        losses += 1
                else:
                    ties += 1
            except:
                ties += 1
        
        results.append({
            "Comparison": f"{a1} vs {a2}",
            "W": wins, "T": ties, "L": losses
        })

    return pd.DataFrame(results)

def generate_report():
    """Main execution function to generate and save all analysis."""
    output_dir = os.path.join(project_root, "results", "analysis_output")
    os.makedirs(output_dir, exist_ok=True)
    
    try:
        df = load_results()
    except Exception as e:
        print(f"[ERROR] {e}")
        return

    for dim in sorted(df["dim"].unique()):
        print(f"\n{'='*40}")
        print(f"  STATISTICAL ANALYSIS FOR D = {dim}")
        print(f"{'='*40}")

        # 1. Mean ± Std Table
        sum_tbl = summary_table(df, dim)
        sum_tbl.to_csv(os.path.join(output_dir, f"summary_table_D{dim}.csv"))
        
        # 2. Friedman Ranking
        rank_df = friedman_ranking(df, dim)
        rank_df.to_csv(os.path.join(output_dir, f"friedman_ranks_D{dim}.csv"), index=False)
        print("\nGlobal Rankings:")
        print(rank_df.to_string(index=False))

        # 3. Wilcoxon W/T/L
        wtl_df = wilcoxon_wtl(df, dim)
        wtl_df.to_csv(os.path.join(output_dir, f"wilcoxon_wtl_D{dim}.csv"), index=False)
        print("\nPairwise Wilcoxon (W/T/L):")
        print(wtl_df.to_string(index=False))

    print(f"\n[v] All analysis files saved in: {output_dir}")

if __name__ == "__main__":
    generate_report()